### ISSUE TITLE
User Story 1 - Flashcard-Demo

### ISSUE THREAD

**Issue by Nesssaaa** [Nesssaaa/Flashcard-App-UserStory#1]
## Value Proposition

As an student
I want to see pairs of information in English and German
So that I can test the app an see how it works

## Description
![Image](https://github.com/Nesssaaa/Flashcard-App-UserStory/assets/148340045/fd6dfa5a-d33b-451a-bbd3-d476556bf7c6)
## Acceptance criteria

- [ ] 4 example cards are shown at the same time
- [ ] Translation appears on click inside the card below the question
- [ ] The cards are shown as a vertically scrollable list
- [ ] Header is always visible

## Tasks

- [ ] Create a data-array in lib/data with 10 example word-pairs
- [ ] Data-array contains: id, the word "welcome" in 4 different languages and the german translation
- [ ] Create component Card to render the Flashcard
- [ ] Create default function HomePage  in “pages/ index.js“ that renders our Card component
- [ ] Create Header component
- [ ] Render Header component in pages/ index.js
- [ ] Card-Container is clickable; answer-paragraph is shown on toggle
